<?php 
include_once("components/header.php");
include_once("components/skils.php");
include_once("components/project.php");
include_once("components/service.php");
?>
<?php 
include_once("components/footer.php");
?>